<%
if request("user_id")<>"" then
user_id=request("user_id")
else
user_id=session("user_id")
end if
dim user(37)
sql = "SELECT * From user where user_id="&user_id
set rs=conn.execute(sql)
user(0)=rs("user_id")
user(1)=rs("user_group_id")
user(2)=rs("user_name")
user(3)=rs("user_pass")
user(4)=rs("user_passts")
user(5)=rs("user_passda")
user(6)=rs("user_oicq")
user(23)=rs("user_msn")
user(24)=rs("user_member")
user(7)=rs("user_mail")
user(8)=rs("user_url")
user(25)=rs("user_url2")
user(9)=rs("user_sf")
user(10)=rs("user_sex")
user(11)=rs("user_bd")
user(12)=rs("user_regtime")
user(13)=rs("user_xm")
user(14)=rs("user_dz")
user(26)=rs("user_dz2")
user(27)=rs("user_dz3")
user(15)=rs("user_yb")
user(16)=rs("user_dl")
user(17)=rs("user_money")
user(18)=rs("user_vip")
user(19)=rs("user_vip_s")
user(20)=rs("user_vip_e")
user(21)=rs("user_ip")
user(22)=rs("user_forum")
user(28)=rs("user_xma")
user(29)=rs("user_urla")
user(30)=rs("user_url2a")
user(31)=rs("user_oicqa")
user(32)=rs("user_msna")
user(33)=rs("user_dza")
user(34)=rs("user_dz2a")
user(35)=rs("user_sfa")
user(36)=rs("user_yba")
user(37)=rs("user_dz3a")
rs.close
set rs=nothing
%>
